THIS IS THE FINAL PROJECT OF THE DATA ANALYST COURSE. 
THE OBJECTIVE IS TO CREATE A ML MODEL THAT CAN PREDICT STOCK PRICES IN THE LONG TERM (1, 3 AND 5 YEARS) USING HISTORICAL DATA.
THE TARGET VARIABLE IS OF COURSE THE PRICE.
THE FEATURE VARIABLES WILL HAVE TO BE CLOSELY EXAMINED AND SELECTED. LONG TERM STOCK PRICESES MAINLY DEPEND ON HOW WELL THE COMPANIES FUNDAMENTAL'S ARE, THE INDUTRY LONG TERM TENDENCY AND THE LONG TERM MACROECONOMIC TENDENCIES. HERE ARE A FEW VARIABLES THAT FOR SURE ARE GOING TO BE RELEVENT ARE THE FOLLOWING:
    1) THE FRIM'S SECTOR
    2) THE AVERAGE STOCK MARKET GROWTH
    3) THE COUNTRY IT'S FROM
    4) P/E RATIO
    5) REVENUE GROWTH
    6) NET INCOME GROWTH
    7) PROFIT MARGIN
    8) DEBT RATIOS

In [10]:
import pandas as pd

SOURCES TO GET DATA FROM

In [11]:
# 1. Company-Level Data (Fundamentals, Price, Sector, Country)

company_data_sources = [
    {
        "Source": "Yahoo Finance (yfinance)",
        "What You Can Get": "Stock prices, P/E, sector, country, market cap, etc.",
        "Notes": "Easiest to use, great for price history and basic fundamentals."
    },
    {
        "Source": "Financial Modeling Prep (FMP)",
        "What You Can Get": "Income statement, balance sheet, ratios, company profile",
        "Notes": "Free tier, clean API, lots of fundamentals."
    },
    {
        "Source": "Alpha Vantage",
        "What You Can Get": "Stock prices, fundamentals, sector data",
        "Notes": "Requires API key (free tier available)."
    },
    {
        "Source": "Quandl",
        "What You Can Get": "Financial statements, macro indicators",
        "Notes": "Some datasets require a subscription."
    },
    {
        "Source": "Kaggle",
        "What You Can Get": "Preprocessed financial datasets",
        "Notes": "Good for exploration, but usually static (not up-to-date)."
    },
    {
        "Source": "EDGAR (SEC)",
        "What You Can Get": "U.S. company filings (10-K, 10-Q)",
        "Notes": "Raw data – not beginner friendly, but very accurate."
    }
]
company_data_sources = pd.DataFrame(company_data_sources)
company_data_sources

,Source,What You Can Get,Notes
0,Yahoo Finance (yfinance),"Stock prices, P/E, sector, country, market cap...","Easiest to use, great for price history and ba..."
1,Financial Modeling Prep (FMP),"Income statement, balance sheet, ratios, compa...","Free tier, clean API, lots of fundamentals."
2,Alpha Vantage,"Stock prices, fundamentals, sector data",Requires API key (free tier available).
3,Quandl,"Financial statements, macro indicators",Some datasets require a subscription.
4,Kaggle,Preprocessed financial datasets,"Good for exploration, but usually static (not ..."
5,EDGAR (SEC),"U.S. company filings (10-K, 10-Q)","Raw data – not beginner friendly, but very acc..."

In [12]:
# 2. Macroeonomic Data

macro_data_sources = [
    {
        "Source": "World Bank Open Data",
        "What You Can Get": "GDP, inflation, debt levels, country-level data",
        "Notes": "Free, downloadable as CSV."
    },
    {
        "Source": "OECD Data",
        "What You Can Get": "Economic indicators for developed countries",
        "Notes": "Useful for long-term trends."
    },
    {
        "Source": "FRED (St. Louis Fed)",
        "What You Can Get": "US interest rates, CPI, employment, etc.",
        "Notes": "Excellent source for macro data."
    },
    {
        "Source": "IMF Data",
        "What You Can Get": "Global economic forecasts and historical data",
        "Notes": "Good for international exposure."
    }
]

macro_data_sources = pd.DataFrame(macro_data_sources)
macro_data_sources

,Source,What You Can Get,Notes
0,World Bank Open Data,"GDP, inflation, debt levels, country-level data","Free, downloadable as CSV."
1,OECD Data,Economic indicators for developed countries,Useful for long-term trends.
2,FRED (St. Louis Fed),"US interest rates, CPI, employment, etc.",Excellent source for macro data.
3,IMF Data,Global economic forecasts and historical data,Good for international exposure.

In [13]:
# 3. Market-Level Data (Indices, ETFs)

market_data_sources = [
    {
        "Source": "Yahoo Finance",
        "What You Can Get": "S&P500, NASDAQ, sector ETFs (e.g. XLF, XLK)",
        "Notes": "Use as proxies for market/sector trend."
    },
    {
        "Source": "MSCI / S&P Sector Indexes",
        "What You Can Get": "Sector-based long-term performance",
        "Notes": "May require manual scraping or static reports."
    },
    {
        "Source": "Kaggle",
        "What You Can Get": "ETF and index datasets",
        "Notes": "Can be used for benchmark comparison."
    }
]
market_data_sources = pd.DataFrame(market_data_sources) 
market_data_sources

,Source,What You Can Get,Notes
0,Yahoo Finance,"S&P500, NASDAQ, sector ETFs (e.g. XLF, XLK)",Use as proxies for market/sector trend.
1,MSCI / S&P Sector Indexes,Sector-based long-term performance,May require manual scraping or static reports.
2,Kaggle,ETF and index datasets,Can be used for benchmark comparison.

In [14]:
total_data_sources = pd.concat([company_data_sources, macro_data_sources, market_data_sources], keys=['Company', 'Macro', 'Market'])
total_data_sources

                                  Source  \
Company 0       Yahoo Finance (yfinance)
        1  Financial Modeling Prep (FMP)
        2                  Alpha Vantage
        3                         Quandl
        4                         Kaggle
        5                    EDGAR (SEC)
Macro   0           World Bank Open Data
        1                      OECD Data
        2           FRED (St. Louis Fed)
        3                       IMF Data
Market  0                  Yahoo Finance
        1      MSCI / S&P Sector Indexes
        2                         Kaggle

                                            What You Can Get  \
Company 0  Stock prices, P/E, sector, country, market cap...
        1  Income statement, balance sheet, ratios, compa...
        2            Stock prices, fundamentals, sector data
        3             Financial statements, macro indicators
        4                    Preprocessed financial datasets
        5                  U.S. company filings (10-K, 10-Q)
Macro   0    GDP, inflation, debt levels, country-level data
        1        Economic indicators for developed countries
        2           US interest rates, CPI, employment, etc.
        3      Global economic forecasts and historical data
Market  0        S&P500, NASDAQ, sector ETFs (e.g. XLF, XLK)
        1                 Sector-based long-term performance
        2                             ETF and index datasets

                                                       Notes
Company 0  Easiest to use, great for price history and ba...
        1        Free tier, clean API, lots of fundamentals.
        2            Requires API key (free tier available).
        3              Some datasets require a subscription.
        4  Good for exploration, but usually static (not ...
        5  Raw data – not beginner friendly, but very acc...
Macro   0                         Free, downloadable as CSV.
        1                       Useful for long-term trends.
        2                   Excellent source for macro data.
        3                   Good for international exposure.
Market  0            Use as proxies for market/sector trend.
        1     May require manual scraping or static reports.
        2              Can be used for benchmark comparison.